#+TITLE: SQLではじめるデータ分析サポートサイト

このサイトは「[[https://www.oreilly.co.jp/books/9784814400201/][SQLではじめるデータ分析 サポートサイト]]」のサポートサイトです。

* 動作環境

本書に掲載されているSQLはPostgreSQLを用いで動作を確認いただけます。ここではDockerを使用し、PostgreSQLの動作環境、及びデータの投入方法の例を紹介します。なおローカルのDocker環境は整備済みであることとします。


** PostgreSQLコンテナの起動と接続

dockerコマンドを使用しDocker Hubからイメージを取得します。ここではサイズの小さいalpineベースのイメージを使用することにしました。

#+caption: PostgreSQLのDockerイメージを取得する
#+begin_src
docker pull postgres:15.0-alpine3.16
#+end_src

#+caption: PostgreSQLのDockerコンテナを起動する
#+begin_src
docker run -d --rm \
    --publish=127.0.0.1:5432:5432 \
    --env=POSTGRES_PASSWORD=postgres \
	--volume=postgres-15-data:/var/lib/postgresql/data \
	--name=postgres \
	postgres:15.0-alpine3.16
#+end_src

起動したコンテナで動作しているPostgreSQLに接続します。ここではdocker execを用いてコンテナ内にあるpsqlコマンドを利用しサーバーに接続します。

#+caption: PostgreSQLサーバーに接続する
#+begin_src bash
docker exec -it postgres psql -U postgres
#+end_src

** テストデータの取得

本書は「[[https://www.oreilly.com/library/view/sql-for-data/9781492088776/][SQL for Data Analysis]]」の翻訳であり、原著の著者がテスト用のデータとSQLをGithub上で公開しています。それらを取得することで、実際に動作をご確認いただけます。

#+caption: テストデータを取得する
#+begin_src bash
git clone https://github.com/cathytanimura/sql_book.git
#+end_src

** データの投入

各フォルダは章毎に分かれています。主に =create_= で始まるファイル名が付いているものは、テーブルを作成する際のDDLが記述されいます。テストデータは、DDLと同じSQLファイルに記載されている場合と、CSV形式で保存されており、DDLのファイルにCOPYコマンドを用いて取り込むようになっている場合があります。



* 正誤表

現在正誤表を準備中です。誤植や間違いなどを見つけた場合、[[mailto:japan@oreilly.co.jp][japan@oreilly.co.jp]]までお知らせください。
